server:
  port: 9527
spring:
  datasource:
    url: xxxxxxx
    username: root
    password: xxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
